# Generated by Django 4.1.2 on 2022-10-18 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Baedin_app', '0004_rename_wuserid_wallet_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.TextField(blank=True, default='', null=True)),
                ('category_icon', models.TextField(blank=True, default='', null=True)),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('isDeleted', models.BooleanField(default=False)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
